### ISSUE TITLE
messaging for notifications

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#57]
based on #54 create copy/messaging for notifications

**Comment by lucwrite** [comment]
ask if wp-quicklatex is activated (depending on whether the book they are importing has equations)
Using equations in your book, activate Quicklatex (Link to plugin)
Rendering issues with wp-quicklatex for the first page load will be slower than usual (for image caching)
If you are using Latex, expect slower loading times for the first time it is accessed due to caching. 
some messaging around large file sizes my take a long time.
This book is a large file and loading times may take longer than usual. Make sure not to close down your browser during this process. (Not sure can we have this triggered based on size? If not we can add an If at the beginning.
