### ISSUE TITLE
Chapters are incorrectly identified as back matter

### ISSUE THREAD

**Issue by greatislander** [BCcampus/pressbooks-openstax-import#63]
### Description 

When importing a given OpenStax book, all chapters are identified as back matter in the importer UI.

**Expected behaviour** 

Front matter, chapters, and back matter should be correctly identified as such.

**Actual behaviour** 

Chapters are identified as back matter.

### Steps to reproduce the problem

Import this book via URL: https://cnx.org/exports/9add9912-c6a7-49a5-8c75-cca4187fdb57@1.1.zip/bitcoin-1.1.zip

<img width="1120" alt="screen shot 2018-06-28 at 2 39 58 pm" src="https://user-images.githubusercontent.com/605361/42051056-2e146878-7ae1-11e8-8340-0b441b8a4102.png">

Observe that chapters are identified as back matter.

### System Information

- Openstax Import for Pressbooks: 1.2.2
- Pressbooks: 5.4.0-dev 
- WordPress: 4.9.6

**Comment by bdolor** [comment]
Do you know of any other books this is happening to? 

Prefacing this with, I would like to migrate this import routine to consume the cnx api instead of the zip file. My expectation is that we would be able to make fewer assumptions about content.

https://github.com/Connexions/cnx-archive/blob/master/docs/content_api_doc.md

The reason this is happening (and I'm going to assume this is either one of the few, or the ?only? book this is happening to) is because of the combination of the way the author has structured their book and the assumptions I've had to make about that structure to map it to different content types (chapter, back-matter, etc). 

the cnx zip file has a manifest, similar to epub/docx/odt ... the xml schema is fairly predictable. This is what most authors do: 

![image](https://user-images.githubusercontent.com/2048170/42604028-7ad50534-8525-11e8-906f-5dba363a9325.png)

these three levels map to front-matter(Preface), part(Welcome to Economics), chapter(What is...) via xpath https://github.com/BCcampus/pressbooks-openstax-import/blob/dev/inc/import/openstax/class-cnx.php#L338

whereas the bitcoin author has kept everything at the same level: 

![image](https://user-images.githubusercontent.com/2048170/42604087-c7b2285a-8525-11e8-92ce-d888f4b4a446.png)
 
this makes what we see expected behaviour, though I agree it could be improved, I'm just not seeing a way to do that by parsing the xml — there's nothing in there except xml structure to distinguish chapters from back-matter. Am hoping that investigating the api will bear some fruit in this direction.

**Comment by greatislander** [comment]
Thanks for the context in terms of how the structure is determined. We only encountered this behaviour with this book, so I think your assessment is correct.

**Comment by bdolor** [comment]
will open a new ticket with regards to api migration, and capture/reference what was discussed here.
